"""Render Asterisk pjsip.conf from the GhostSIP JSON config.

Only pjsip.conf is generated from the GUI (handsets + trunk-back seat), since
that is the part that changes as phones are added. extensions.conf, http.conf
and ari.conf are static and live in ../asterisk/.

Output path: GHOSTSIP_PJSIP_PATH env var, else /etc/asterisk/pjsip.conf.
"""

from __future__ import annotations

import os

PJSIP_PATH = os.environ.get("GHOSTSIP_PJSIP_PATH", "/etc/asterisk/pjsip.conf")

_HEADER = """;=============================================================================
; GhostSIP pjsip.conf — GENERATED by the admin panel. Do not hand-edit;
; changes are overwritten on the next save. Edit via the web GUI instead.
;=============================================================================

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:{port}
; lets a port change from the panel apply on 'pjsip reload'
allow_reload=yes

[vvx-endpoint](!)
type=endpoint
context=from-phones
disallow=all
allow=ulaw
allow=alaw
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[vvx-auth](!)
type=auth
auth_type=userpass

[vvx-aor](!)
type=aor
max_contacts=1
remove_existing=yes
qualify_frequency=60
"""

_HANDSET_TPL = """
;--- {name} ---
[{ep}](vvx-endpoint)
auth={ep}
aors={ep}

[{ep}](vvx-auth)
username={ep}
password={pw}

[{ep}](vvx-aor)
"""

_TRUNK_TPL = """
;----------------------------------------------------------------------------
; Trunk-back seat: Asterisk registers to VoIPstudio for callback relay.
;----------------------------------------------------------------------------
[voipstudio-reg]
type=registration
outbound_auth=voipstudio-auth
server_uri=sip:{server}
client_uri=sip:{user}@{server}
retry_interval=60
forbidden_retry_interval=300
expiration=300
line=yes
endpoint=voipstudio

[voipstudio-auth]
type=auth
auth_type=userpass
username={user}
password={pw}

[voipstudio]
type=endpoint
context=from-voipstudio
outbound_auth=voipstudio-auth
aors=voipstudio
disallow=all
allow=ulaw
allow=alaw
from_user={user}
from_domain={server}
direct_media=no
rtp_symmetric=yes

[voipstudio]
type=aor
contact=sip:{server}

[voipstudio-identify]
type=identify
endpoint=voipstudio
match={server}
"""


def render(config: dict) -> str:
    port = int(config.get("sip", {}).get("port") or 5560)
    parts = [_HEADER.format(port=port)]
    for hs in config.get("handsets", []):
        ep = (hs.get("endpoint") or "").strip()
        if not ep:
            continue
        parts.append(
            _HANDSET_TPL.format(
                name=hs.get("name") or ep,
                ep=ep,
                pw=hs.get("password") or "",
            )
        )
    trunk = config.get("trunkback", {})
    if trunk.get("username"):
        parts.append(
            _TRUNK_TPL.format(
                server=trunk.get("server") or "sip.voipstudio.com",
                user=trunk["username"],
                pw=trunk.get("password") or "",
            )
        )
    return "".join(parts)


def write(config: dict) -> str:
    """Render and write pjsip.conf. Returns the path written."""
    text = render(config)
    os.makedirs(os.path.dirname(PJSIP_PATH) or ".", exist_ok=True)
    tmp = f"{PJSIP_PATH}.tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(text)
    os.replace(tmp, PJSIP_PATH)
    return PJSIP_PATH
