# Generated by Django 5.2.17 on 2026-08-14 06:13

import django.core.validators
import panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_username', models.CharField(blank=True, help_text='Must match the Basic Auth embedded in the VoIPstudio webhook URL: https://USER:PASS@your-domain/webhook', max_length=100, validators=[panel.models._no_linebreaks])),
                ('webhook_password', models.CharField(blank=True, default=panel.models.generate_secret, max_length=100, validators=[panel.models._no_linebreaks])),
                ('sip_port', models.PositiveIntegerField(default=5560, help_text="UDP port the phones register to. Non-standard on purpose (scanner noise). Must match each phone's server port and the firewall rule; a change needs a stack restart.", validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)])),
                ('ring_seconds', models.PositiveIntegerField(default=4, help_text='How long a ghost call rings before Asterisk cancels it.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('caller_name_prefix', models.CharField(blank=True, help_text="Shown before the number in the missed-call entry so ghost calls match VoIPstudio's ring-group-name prepend (e.g. TechRescue). Callback always dials the bare number.", max_length=60)),
                ('alert_info', models.CharField(blank=True, help_text='Optional value mapped to a silent ring class on the VVX. Empty = off.', max_length=100, validators=[panel.models._no_linebreaks], verbose_name='Alert-Info header')),
                ('include_user_context', models.BooleanField(default=False, help_text='Also inject for missed direct (User-context) calls, not just ring-group.', verbose_name='Inject for direct calls too')),
                ('debug_log_payloads', models.BooleanField(default=False, help_text='Commissioning aid (test A): records raw webhook JSON including caller numbers. Turn OFF in normal use — numbers are otherwise masked.', verbose_name='Debug: log full payloads')),
                ('trunk_server', models.CharField(default='sip.voipstudio.com', max_length=200, validators=[panel.models._no_linebreaks])),
                ('trunk_username', models.CharField(blank=True, max_length=100, validators=[panel.models._no_linebreaks])),
                ('trunk_password', models.CharField(blank=True, max_length=100, validators=[panel.models._no_linebreaks])),
                ('pushover_enabled', models.BooleanField(default=False)),
                ('pushover_user_key', models.CharField(blank=True, max_length=100, validators=[panel.models._no_linebreaks])),
                ('pushover_api_token', models.CharField(blank=True, max_length=100, validators=[panel.models._no_linebreaks])),
                ('alert_on_errors', models.BooleanField(default=False, help_text='Normal-priority push when an ERROR is recorded (rate-limited to one per 15 minutes).')),
                ('alert_on_new_registration', models.BooleanField(default=True, help_text="Push when a phone's credential authenticates from an address it has never used before. Routine re-registrations stay silent.", verbose_name='Alert on new device address')),
                ('lockdown_active', models.BooleanField(default=False, editable=False)),
                ('lockdown_auto_enabled', models.BooleanField(default=False, help_text='Engage lockdown automatically when a credential authenticates from a never-seen address. Arm AFTER first rollout. Never triggered by failed attempts (that would let outsiders switch callbacks off).', verbose_name='Auto-lockdown')),
                ('lockdown_suspend_until', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'configuration',
                'verbose_name_plural': 'configuration',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, max_length=10)),
                ('kind', models.CharField(choices=[('webhook', 'Webhook'), ('injection', 'Injection'), ('security', 'Security'), ('lockdown', 'Lockdown'), ('system', 'System')], db_index=True, max_length=12)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Handset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Free text, e.g. 'Front desk'.", max_length=100)),
                ('endpoint', models.CharField(help_text='PJSIP endpoint name = the SIP username on the phone (e.g. phone1).', max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]{1,40}$', 'Letters, digits, - and _ only (max 40).')])),
                ('sip_password', models.CharField(default=panel.models.generate_secret, help_text="Auto-generated. Copy into the phone's GhostSIP line.", max_length=100)),
            ],
            options={
                'ordering': ['endpoint'],
            },
        ),
        migrations.CreateModel(
            name='InjectedCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_call_id', models.CharField(max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnownAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'known addresses',
                'constraints': [models.UniqueConstraint(fields=('endpoint', 'ip'), name='unique_endpoint_ip')],
            },
        ),
    ]
