"""Render Asterisk pjsip.conf from the database (Configuration + Handsets).

Written to the persistent /etc/ghostsip volume; the image's stub
/etc/asterisk/pjsip.conf includes it. Regenerated on every admin save of
Configuration or a Handset; applied by the Reload Asterisk button."""

from __future__ import annotations

import os

PJSIP_PATH = os.environ.get("GHOSTSIP_PJSIP_PATH", "/etc/ghostsip/pjsip.conf")

_HEADER = """;=============================================================================
; GhostSIP pjsip.conf — GENERATED by the admin panel. Do not hand-edit;
; changes are overwritten on the next save. Edit via the admin instead.
;=============================================================================

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:{port}
; lets a port change from the panel apply on 'pjsip reload'
allow_reload=yes

[vvx-endpoint](!)
type=endpoint
context=from-phones
disallow=all
allow=ulaw
allow=alaw
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
{from_domain_line}
[vvx-auth](!)
type=auth
auth_type=userpass

[vvx-aor](!)
type=aor
max_contacts=1
remove_existing=yes
qualify_frequency=60
"""

_HANDSET_TPL = """
;--- {name} ---
[{ep}](vvx-endpoint)
auth={ep}
aors={ep}

[{ep}](vvx-auth)
username={ep}
password={pw}

[{ep}](vvx-aor)
"""

_TRUNK_TPL = """
;----------------------------------------------------------------------------
; Trunk-back seat: Asterisk registers to VoIPstudio for callback relay.
;----------------------------------------------------------------------------
[voipstudio-reg]
type=registration
outbound_auth=voipstudio-auth
server_uri=sip:{server}
client_uri=sip:{user}@{server}
retry_interval=60
forbidden_retry_interval=300
expiration=300
line=yes
endpoint=voipstudio

[voipstudio-auth]
type=auth
auth_type=userpass
username={user}
password={pw}

[voipstudio]
type=endpoint
context=from-voipstudio
outbound_auth=voipstudio-auth
aors=voipstudio
disallow=all
allow=ulaw
allow=alaw
from_user={user}
from_domain={server}
direct_media=no
rtp_symmetric=yes

[voipstudio]
type=aor
contact=sip:{server}

[voipstudio-identify]
type=identify
endpoint=voipstudio
match={server}
"""


def render(config, handsets) -> str:
    port = int(config.sip_port)
    # Ghost INVITEs carry this as the From domain, so the URI a phone stores
    # in its missed-call entry is sip:<number>@<domain>:<port>. Without the
    # explicit port, a tap-to-callback that honours the URI would aim at SIP
    # default 5060 — where nothing listens (found live: callbacks died
    # silently). With it, callbacks land on the real listener.
    domain = os.environ.get("GHOSTSIP_DOMAIN", "")
    from_domain_line = f"from_domain={domain}:{port}\n" if domain else ""
    parts = [_HEADER.format(port=port, from_domain_line=from_domain_line)]
    for hs in handsets:
        parts.append(_HANDSET_TPL.format(name=hs.name or hs.endpoint, ep=hs.endpoint, pw=hs.sip_password))
    if config.trunk_username:
        parts.append(
            _TRUNK_TPL.format(
                server=config.trunk_server or "sip.voipstudio.com",
                user=config.trunk_username,
                pw=config.trunk_password,
            )
        )
    return "".join(parts)


def write(config, handsets) -> str:
    """Render and atomically write pjsip.conf. Returns the path written."""
    text = render(config, handsets)
    os.makedirs(os.path.dirname(PJSIP_PATH) or ".", exist_ok=True)
    tmp = f"{PJSIP_PATH}.tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(text)
    os.replace(tmp, PJSIP_PATH)
    return PJSIP_PATH
